### ISSUE TITLE
Allow user to create their own placeholders in the cargo-generate.toml file.

### ISSUE THREAD

**Issue by seanybaggins** [ashleygwilliams/cargo-generate#257] opened 2020-11-05 19:42 UTC
It would be nice if users can create their own placeholders so cargo generate can be used for more than just rust projects.

Example 
```cargo-generate.toml
[template]
rust_project = false

[placeholders]
SOME_PLACEHOLDER = "Prompt to user"
SERVER_NAME = "Enter the domain name for your server: "
```

```Docker_Stack.yaml
services:
  jenkins:
    ...
  nginx:
    environment:
      SERVER_NAME: {{SERVER_NAME}}
    ...
```

Running `cargo generate --git <DOCKER_STACK_REPO>`
would trigger the typical prompts and...
```
Enter the domain name for your server: 
```

**Comment by MarcoIeni** [comment] 2020-12-27 19:43
duplicate of #17

**Comment by k0pernicus** [comment] 2021-01-10 10:02
Closing it as duplicate of #17.

Please to contribute to the original issue @seanybaggins :)  
Thanks in advance

**Closed by k0pernicus** 2021-01-10 10:02 UTC
Labels: duplicate
